var data = {
  'SUBSECRETARIAS': {
    'UNIDADMONITOREO': {
      'NOMBRE': 'UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE',
      'DIRECTOR': '',
      'OFICINAPRIVADA': {
        'NOMBRE': 'OFICINA PRIVADA DE UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE',
        'DIRECTOR': ''
      }
    },
    'DIRECCIONCOMUNICACION': {
      'NOMBRE': 'DIRECCIÓN DE COMUNICACIÓN Y RELACIÓN INSTITUCIONALES',
      'DIRECTOR': '',
      'OFICINAPRIVADA': {
        'NOMBRE': 'OFICINA PRIVADA DE DIRECCIÓN DE COMUNICACIÓN Y RELACIÓN INSTITUCIONALES',
        'DIRECTOR': ''
      }
    },
    'SUBSECRETARIATRANSPORTETERRESTRE': {
      'NOMBRE': 'SUBSECRETARÍA DE TRANSPORTE TERRESTRE',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE LA SUBSECRETARÍA DE TRANSPORTE TERRESTRE',
          'DIRECTOR': ''
        },
        'DIRECCIONFISCALIZACIONTRANSPORTE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE FISCALIZACIÓN DEL TRANSPORTE',
          'DIRECCIONES': {
            'DIRECCIONFISCALIZACIONTRANSPORTE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCION',
              'DIRECTOR': ''
            },
            'DIRECCIÓNCONTROLTECNICO': {
              'NOMBRE': 'DIRECCIÓN DE CONTROL TÉCNICO',
              'DIRECTOR': ''
            },
            'DIRECCIÓNRECLAMOSSOLICITUDES': {
              'NOMBRE': 'DIRECCIÓN DE RECLAMOS Y SOLICITUDES',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONTRANSPORTEPASAJEROS': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE PASAJEROS',
          'DIRECCIONES': {
            'DIRECCIONTRANSPORTEPASAJEROS': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIÓNTRANSPORTEAUTOMOTORPASAJEROS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE PASAJEROS',
              'DIRECTOR': ''
            },
            'DIRECCIONPERMISOSHABILITACIONESPASAJEROS': {
              'NOMBRE': 'DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE PASAJEROS',
              'DIRECTOR': ''
            },
            'DIRECCIONTRANSPORTEFERROVIARIOPASAJEROS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE FERROVIARIO DE PASAJEROS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONTRANSPORTECARGAS': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE CARGAS',
          'DIRECCIONES': {
            'DIRECCIONTRANSPORTECARGAS': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONPERMISOSHABILITACIONESCARGAS': {
              'NOMBRE': 'DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE CARGAS',
              'DIRECTOR': ''
            },
            'DIRECCIONTRANSPORTEAUTOMOTORCARGAS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE CARGAS',
              'DIRECTOR': ''
            },
            'DIRECCIONTRANSPORTEFERROVIARIOCARGAS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE FERROVIARIO DE CARGAS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONAPTITUDCONDUCTORES': {
          'NOMBRE': 'DIRECCION PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO',
          'OFICINAPRIVADA': {
            'NOMBRE': 'OFICINA PRIVADA DE DIRECCION PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO',
            'DIRECTOR': ''
          },
          'DIRECTOR': ''
        },
        'DIRECCIONPOLITICASTRANSPORTESOSTENIBLE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE POLÍTICAS DE TRANSPORTE SOSTENIBLE',
          'DIRECCIONES': {
            'DIRECCIONPOLITICASTRANSPORTESOSTENIBLE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONDESARROLLOSOSTENIBLETRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE DESARROLLO SOSTENIBLE DEL TRANSPORTE',
              'DIRECTOR': ''
            },
            'DIRECCIONPROYECTOSESTRATEGICOS': {
              'NOMBRE': 'DIRECCIÓN DE PROYECTOS ESTRATÉGICOS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONVERIFICACIONTECNICAVEHICULAR': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE VERIFICACIÓN TÉCNICA VEHICULAR',
          'DIRECCIONES': {
            'DIRECCIONVERIFICACIONTECNICAVEHICULAR': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONAPOYOLEGALTECNICOADMIN': {
              'NOMBRE': 'DIRECCIÓN DE APOYO LEGAL Y TÉCNICO ADMINISTRATIVO',
              'DIRECTOR': ''
            },
            'DIRECCIONPLANIFICACIONCOORDSERVICIO': {
              'NOMBRE': 'DIRECCIÓN DE PLANIFICACIÓN Y COORDINACIÓN DEL SERVICIO',
              'DIRECTOR': ''
            },
            'DIRECCIONFISCALIZACIONCONTROL': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN Y CONTROL',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        }
      },
      'DIRECTOR': ''
    },
    'SUBSECRETARIAPOLITICASEGURIDADVIAL': {
      'NOMBRE': 'SUBSECRETARÍA DE POLÍTICA Y SEGURIDAD VIAL',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA DE POLÍTICA Y SEGURIDAD VIAL',
          'DIRECTOR': ''
        },
        'DIRECCIONLICENCIASCONDUCIRANTECEDENTESTRANSITO': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE LICENCIAS DE CONDUCIR Y ANTECEDENTES DE TRÁNSITO',
          'DIRECCIONES': {
            'DIRECCIONLICENCIASCONDUCIRANTECEDENTESTRANSITO': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONLICENCIASCONDUCIR': {
              'NOMBRE': 'DIRECCIÓN DE LICENCIAS DE CONDUCIR',
              'DIRECTOR': ''
            },
            'DIRECCIONANTECEDENTESINHABILITADOS': {
              'NOMBRE': 'DIRECCIÓN DE ANTECEDENTES E INHABILITADOS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONOBSERVATORIOVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE OBSERVATORIO VIAL',
          'DIRECCIONES': {
            'DIRECCIONOBSERVATORIOVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONESTADISTICAVIAL': {
              'NOMBRE': 'DIRECCIÓN DE ESTADÍSTICA VIAL',
              'DIRECTOR': ''
            },
            'DIRECCIONCAPACITACIONENLACECOMUNITARIO': {
              'NOMBRE': 'DIRECCIÓN DE CAPACITACIÓN Y ENLACE COMUNITARIO',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONFISCALIZACIONCONTROLTRANSITOSEGURIDADVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE FISCALIZACIÓN Y CONTROL DEL TRÁNSITO Y LA SEGURIDAD VIAL',
          'DIRECCIONES': {
            'DIRECCIONFISCALIZACIONCONTROLTRANSITOSEGURIDADVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONFISCALIZACIONCONTROLTRANSITO': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN Y CONTROL DEL TRÁNSITO',
              'DIRECTOR': ''
            },
            'DIRECCIONSEGURIDADVIAL': {
              'NOMBRE': 'DIRECCIÓN DE SEGURIDAD VIAL',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONAPOYOCOORDTECNICOADMINISTRATIVA': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE APOYO Y COORDINACIÓN TÉCNICO ADMINISTRATIVA',
          'DIRECCIONES': {
            'JUZGADOSADMINISTRATIVOS': {
              'NOMBRE': 'JUZGADOS ADMINISTRATIVOS DE INFRACCIONES DE TRÁNSITO PROVINCIAL (I A XIII)',
              'DIRECTOR': ''
            },
            'DIRECCIONAPOYOADMINISTRATIVO': {
              'NOMBRE': 'DIRECCIÓN DE APOYO ADMINISTRATIVO',
              'DIRECTOR': ''
            },
            'DIRECCIONCOORDINACIONJUSTICIAADMINISTRATIVA': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN Y ORGANIZACIÓN DE LA JUSTICIA ADMINISTRATIVA DE INFRACCIONES DE TRÁNSITO PROVINCIAL',
              'DIRECTOR': ''
            },
            'DIRECCIONINFORMATICATECNOLOGIA': {
              'NOMBRE': 'DIRECCIÓN DE INFORMÁTICA Y TECNOLOGÍA',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        }
      },
      'DIRECTOR': ''
    },
    'SUBSECRETARIATECNICAADMINISTRATIVALEGAL': {
      'NOMBRE': 'SUBSECRETARÍA TÉCNICA ADMINISTRATIVA Y LEGAL',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA TÉCNICA ADMINISTRATIVA Y LEGAL',
          'DIRECTOR': ''
        },
        'DIRECCIONGENERALADMINISTRACION': {
          'NOMBRE': 'DIRECCIÓN GENERAL DE ADMINISTRACIÓN',
          'DIRECCIONES': {
            'DIRECCIONGENERALADMINISTRACION': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONCONTABILIDAD': {
              'NOMBRE': 'DIRECCIÓN DE CONTABILIDAD',
              'DIRECTOR': ''
            },
            'DIRECCIONPRESUPUESTO': {
              'NOMBRE': 'DIRECCIÓN DE PRESUPUESTO',
              'DIRECTOR': ''
            },
            'DIRECCIONCOMPRASCONTRATACIONESSUMINISTROS': {
              'NOMBRE': 'DIRECCIÓN DE COMPRAS, CONTRATACIONES Y SUMINISTROS',
              'DIRECTOR': ''
            },
            'DIRECCIONTESORERIA': {
              'NOMBRE': 'DIRECCIÓN DE TESORERÍA',
              'DIRECTOR': ''
            },
            'DIRECCIONDELEGADAPERSONAL': {
              'NOMBRE': 'DIRECCIÓN DELEGADA DE LA DIRECCIÓN PROVINCIAL DE PERSONAL',
              'DIRECTOR': ''
            },
            'DIRECCIONTECNOLOGIAINFORMACION': {
              'NOMBRE': 'DIRECCIÓN DE TECNOLOGÍA DE LA INFORMACIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONSERVICIOSAUXILIARES': {
              'NOMBRE': 'DIRECCIÓN DE SERVICIOS AUXILIARES',
              'DIRECTOR': ''
            },
            'DIRECCIONSERVICIOSTECNICOS': {
              'NOMBRE': 'DIRECCIÓN DE SERVICIOS TÉCNICOS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONGENERALTECNICALEGAL': {
          'NOMBRE': 'DIRECCIÓN GENERAL TÉCNICA Y LEGAL',
          'DIRECCIONES': {
            'DIRECCIONGENERALTECNICALEGAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONTECNICOADMINISTRATIVA': {
              'NOMBRE': 'DIRECCIÓN TÉCNICO ADMINISTRATIVA',
              'DIRECTOR': ''
            },
            'DIRECCIONCOORDINACIONJURIDICA': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN JURÍDICA',
              'DIRECTOR': ''
            },
            'DIRECCIONGESTIONMULTAS': {
              'NOMBRE': 'DIRECCIÓN DE GESTIÓN DE MULTAS POR INFRACCIONES DE TRÁNSITO Y TRANSPORTE',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        }
      },
      'DIRECTOR': ''
    },
    'SUBSECRETARIATRANSPORTEAEREOFLUVIAL': {
      'NOMBRE': 'SUBSECRETARÍA DE TRANSPORTE AÉREO Y FLUVIAL',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA DE TRANSPORTE AÉREO Y FLUVIAL',
          'DIRECTOR': ''
        },
        'DIRECCIONCONTRALORTRANSPORTEFLUVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE FLUVIAL DE PASAJEROS',
          'DIRECCIONES': {
            'DIRECCIONCONTRALORTRANSPORTEFLUVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONOPERACIONESTRANSPORTEFLUVIAL': {
              'NOMBRE': 'DIRECCIÓN DE OPERACIONES DE TRANSPORTE FLUVIAL DE PASAJEROS',
              'DIRECTOR': ''
            },
            'DIRECCIONFISCALIZACIONTRANSPORTEFLUVIAL': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN DEL TRANSPORTE FLUVIAL DE PASAJEROS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONCONTRALORTRANSPORTEAEREO': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE AÉREO',
          'DIRECCIONES': {
            'DIRECCIONCONTRALORTRANSPORTEAEREO': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONOPERACIONESTRANSPORTEAEREO': {
              'NOMBRE': 'DIRECCIÓN DE OPERACIONES DEL TRANSPORTE AÉREO',
              'DIRECTOR': ''
            },
            'DIRECCIONFISCALIZACIONAEROPORTUARIA': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN AEROPORTUARIA',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONPROMOCIONCOORDINACIONTRANSPORTEAEREOFLUVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE PROMOCIÓN Y COORDINACIÓN DEL TRANSPORTE AÉREO Y FLUVIAL',
          'DIRECCIONES': {
            'DIRECCIONPROMOCIONCOORDINACIONTRANSPORTEAEREOFLUVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONESTRATEGIASPORTUARIASAEROPORTUARIAS': {
              'NOMBRE': 'DIRECCIÓN DE ESTRATEGIAS PORTUARIAS Y AEROPORTUARIAS',
              'DIRECTOR': ''
            },
            'DIRECCIONPROMOCIONDESARROLLOTRANSPORTEFLUVIAL': {
              'NOMBRE': 'DIRECCIÓN DE PROMOCIÓN Y DESARROLLO DE TRANSPORTE FLUVIAL DE PASAJEROS',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        }
      },
      'DIRECTOR': ''
    },
    'SUBSECRETARIAARTICULACIONINTERJURISDICCIONAL': {
      'NOMBRE': 'SUBSECRETARÍA DE ARTICULACIÓN INTERJURISDICCIONAL DEL TRANSPORTE',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA DE ARTICULACIÓN INTERJURISDICCIONAL',
          'DIRECTOR': ''
        },
        'DIRECCIONCOMPENSACIONESTRANSPORTE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE COMPENSACIONES AL TRANSPORTE',
          'DIRECCIONES': {
            'DIRECCIONCOMPENSACIONESTRANSPORTE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONLIQUIDACIONPAGO': {
              'NOMBRE': 'DIRECCIÓN DE LIQUIDACIÓN Y PAGO',
              'DIRECTOR': ''
            },
            'DIRECCIONCONTROLVERIFICACION': {
              'NOMBRE': 'DIRECCIÓN DE CONTROL Y VERIFICACIÓN',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONCOORDINACIONTRANSPORTE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE COORDINACIÓN DEL TRANSPORTE',
          'DIRECCIONES': {
            'DIRECCIONCOORDINACIONTRANSPORTE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONCOORDINACIONPUBLICO': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PÚBLICO',
              'DIRECTOR': ''
            },
            'DIRECCIONCOORDINACIONPRIVADO': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PRIVADO',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONPLANIFICACIONPOLITICAECONOMICA': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE PLANIFICACIÓN Y POLÍTICA ECONÓMICA DEL TRANSPORTE',
          'DIRECCIONES': {
            'DIRECCIONPLANIFICACIONPOLITICAECONOMICA': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONPLANIFICACIONTRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE PLANIFICACIÓN DEL TRANSPORTE',
              'DIRECTOR': ''
            },
            'DIRECCIONANALISISTRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE ANÁLISIS EFICIENTE DEL TRANSPORTE',
              'DIRECTOR': ''
            },
            'DIRECCIONGESTIONSUBSIDIOS': {
              'NOMBRE': 'DIRECCIÓN DE GESTIÓN DE SUBSIDIOS AL TRANSPORTE',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONPOLITICASGENEROINCLUSIVAS': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE POLÍTICAS DE GÉNERO Y ESTRATEGIAS INCLUSIVAS',
          'DIRECCIONES': {
            'DIRECCIONPOLITICASGENEROINCLUSIVAS': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONACCESIBILIDADTRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE ACCESIBILIDAD DEL TRANSPORTE',
              'DIRECTOR': ''
            },
            'DIRECCIONINCLUSIONDIVERSIDAD': {
              'NOMBRE': 'DIRECCIÓN DE INCLUSIÓN Y DIVERSIDAD',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONPOLITICASEDUCATIVASPREVENCION': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE POLÍTICAS EDUCATIVAS DE PREVENCIÓN',
          'DIRECCIONES': {
            'DIRECCIONPOLITICASEDUCATIVASPREVENCION': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',
              'DIRECTOR': ''
            },
            'DIRECCIONPROMOCIONNORMASCONVIVENCIA': {
              'NOMBRE': 'DIRECCIÓN DE PROMOCIÓN DE NORMAS DE CONVIVENCIA CIUDADANA',
              'DIRECTOR': ''
            },
            'DIRECCIONGESTIONINTERMINISTERIAL': {
              'NOMBRE': 'DIRECCIÓN DE GESTIÓN INTERMINISTERIAL DE PREVENCIÓN Y CONCIENTIZACIÓN EN EL TRANSPORTE',
              'DIRECTOR': ''
            }
          },
          'DIRECTOR': ''
        }
      },
      'DIRECTOR': ''
    }
  }
}