var data = {
  "SUBSECRETARIAS": {
    "UNIDADMONITOREO": {
      "NOMBRE": "UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE",
      "DIRECTOR": "RUBIO, LISANDRO",
      "OFICINAPRIVADA": {
        "NOMBRE": "OFICINA PRIVADA DE UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE"
      }
    },
    "DIRECCIONCOMUNICACION": {
      "NOMBRE": "DIRECCIÓN DE COMUNICACIÓN Y RELACIÓN INSTITUCIONALES",
      "DIRECTOR": "CAMETHO, MARÍA VIOLETA",
      "OFICINAPRIVADA": {
        "NOMBRE": "OFICINA PRIVADA DE DIRECCIÓN DE COMUNICACIÓN Y RELACIÓN INSTITUCIONALES"
      }
    },
    "SUBSECRETARIATRANSPORTETERRESTRE": {
      "NOMBRE": "SUBSECRETARÍA DE TRANSPORTE TERRESTRE",
      "DIRECCIONES": {
        "OFICINAPRIVADA": {
          "NOMBRE": "OFICINA PRIVADA DE LA SUBSECRETARÍA DE TRANSPORTE TERRESTRE"
        },
        "DIRECCIONFISCALIZACIONTRANSPORTE": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE FISCALIZACIÓN DEL TRANSPORTE",
          "DIRECCIONES": {
            "DIRECCIONFISCALIZACIONTRANSPORTE": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCION"
            },
            "DIRECCIÓNCONTROLTECNICO": {
              "NOMBRE": "DIRECCIÓN DE CONTROL TÉCNICO"
            },
            "DIRECCIÓNRECLAMOSSOLICITUDES": {
              "NOMBRE": "DIRECCIÓN DE RECLAMOS Y SOLICITUDES"
            }
          }
        },
        "DIRECCIONTRANSPORTEPASAJEROS": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE TRANSPORTE DE PASAJEROS",
          "DIRECCIONES": {
            "DIRECCIONTRANSPORTEPASAJEROS": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIÓNTRANSPORTEAUTOMOTORPASAJEROS": {
              "NOMBRE": "DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE PASAJEROS"
            },
            "DIRECCIONPERMISOSHABILITACIONESPASAJEROS": {
              "NOMBRE": "DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE PASAJEROS"
            },
            "DIRECCIONTRANSPORTEFERROVIARIOPASAJEROS": {
              "NOMBRE": "DIRECCIÓN DE TRANSPORTE FERROVIARIO DE PASAJEROS"
            }
          }
        },
        "DIRECCIONTRANSPORTECARGAS": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE TRANSPORTE DE CARGAS",
          "DIRECCIONES": {
            "DIRECCIONTRANSPORTECARGAS": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONPERMISOSHABILITACIONESCARGAS": {
              "NOMBRE": "DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE CARGAS"
            },
            "DIRECCIONTRANSPORTEAUTOMOTORCARGAS": {
              "NOMBRE": "DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE CARGAS"
            },
            "DIRECCIONTRANSPORTEFERROVIARIOCARGAS": {
              "NOMBRE": "DIRECCIÓN DE TRANSPORTE FERROVIARIO DE CARGAS"
            }
          }
        },
        "DIRECCIONAPTITUDCONDUCTORES": {
          "NOMBRE": "DIRECCION PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO",
          "OFICINAPRIVADA": {
            "NOMBRE": "OFICINA PRIVADA DE DIRECCION PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO"
          }
        },
        "DIRECCIONPOLITICASTRANSPORTESOSTENIBLE": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE POLÍTICAS DE TRANSPORTE SOSTENIBLE",
          "DIRECCIONES": {
            "DIRECCIONPOLITICASTRANSPORTESOSTENIBLE": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONDESARROLLOSOSTENIBLETRANSPORTE": {
              "NOMBRE": "DIRECCIÓN DE DESARROLLO SOSTENIBLE DEL TRANSPORTE"
            },
            "DIRECCIONPROYECTOSESTRATEGICOS": {
              "NOMBRE": "DIRECCIÓN DE PROYECTOS ESTRATÉGICOS"
            }
          }
        },
        "DIRECCIONVERIFICACIONTECNICAVEHICULAR": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE VERIFICACIÓN TÉCNICA VEHICULAR",
          "DIRECCIONES": {
            "DIRECCIONVERIFICACIONTECNICAVEHICULAR": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONAPOYOLEGALTECNICOADMIN": {
              "NOMBRE": "DIRECCIÓN DE APOYO LEGAL Y TÉCNICO ADMINISTRATIVO"
            },
            "DIRECCIONPLANIFICACIONCOORDSERVICIO": {
              "NOMBRE": "DIRECCIÓN DE PLANIFICACIÓN Y COORDINACIÓN DEL SERVICIO"
            },
            "DIRECCIONFISCALIZACIONCONTROL": {
              "NOMBRE": "DIRECCIÓN DE FISCALIZACIÓN Y CONTROL"
            }
          }
        }
      }
    },
    "SUBSECRETARIAPOLITICASEGURIDADVIAL": {
      "NOMBRE": "SUBSECRETARÍA DE POLÍTICA Y SEGURIDAD VIAL",
      "DIRECCIONES": {
        "OFICINAPRIVADA": {
          "NOMBRE": "OFICINA PRIVADA DE SUBSECRETARÍA DE POLÍTICA Y SEGURIDAD VIAL"
        },
        "DIRECCIONLICENCIASCONDUCIRANTECEDENTESTRANSITO": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE LICENCIAS DE CONDUCIR Y ANTECEDENTES DE TRÁNSITO",
          "DIRECCIONES": {
            "DIRECCIONLICENCIASCONDUCIRANTECEDENTESTRANSITO": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONLICENCIASCONDUCIR": {
              "NOMBRE": "DIRECCIÓN DE LICENCIAS DE CONDUCIR"
            },
            "DIRECCIONANTECEDENTESINHABILITADOS": {
              "NOMBRE": "DIRECCIÓN DE ANTECEDENTES E INHABILITADOS"
            }
          }
        },
        "DIRECCIONOBSERVATORIOVIAL": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE OBSERVATORIO VIAL",
          "DIRECCIONES": {
            "DIRECCIONOBSERVATORIOVIAL": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONESTADISTICAVIAL": {
              "NOMBRE": "DIRECCIÓN DE ESTADÍSTICA VIAL"
            },
            "DIRECCIONCAPACITACIONENLACECOMUNITARIO": {
              "NOMBRE": "DIRECCIÓN DE CAPACITACIÓN Y ENLACE COMUNITARIO"
            }
          }
        },
        "DIRECCIONFISCALIZACIONCONTROLTRANSITOSEGURIDADVIAL": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE FISCALIZACIÓN Y CONTROL DEL TRÁNSITO Y LA SEGURIDAD VIAL",
          "DIRECCIONES": {
            "DIRECCIONFISCALIZACIONCONTROLTRANSITOSEGURIDADVIAL": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONFISCALIZACIONCONTROLTRANSITO": {
              "NOMBRE": "DIRECCIÓN DE FISCALIZACIÓN Y CONTROL DEL TRÁNSITO"
            },
            "DIRECCIONSEGURIDADVIAL": {
              "NOMBRE": "DIRECCIÓN DE SEGURIDAD VIAL"
            }
          }
        },
        "DIRECCIONAPOYOCOORDTECNICOADMINISTRATIVA": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE APOYO Y COORDINACIÓN TÉCNICO ADMINISTRATIVA",
          "DIRECCIONES": {
            "JUZGADOSADMINISTRATIVOS": {
              "NOMBRE": "JUZGADOS ADMINISTRATIVOS DE INFRACCIONES DE TRÁNSITO PROVINCIAL (I A XIII)"
            },
            "DIRECCIONAPOYOADMINISTRATIVO": {
              "NOMBRE": "DIRECCIÓN DE APOYO ADMINISTRATIVO"
            },
            "DIRECCIONCOORDINACIONJUSTICIAADMINISTRATIVA": {
              "NOMBRE": "DIRECCIÓN DE COORDINACIÓN Y ORGANIZACIÓN DE LA JUSTICIA ADMINISTRATIVA DE INFRACCIONES DE TRÁNSITO PROVINCIAL"
            },
            "DIRECCIONINFORMATICATECNOLOGIA": {
              "NOMBRE": "DIRECCIÓN DE INFORMÁTICA Y TECNOLOGÍA"
            }
          }
        }
      }
    },
    "SUBSECRETARIATECNICAADMINISTRATIVALEGAL": {
      "NOMBRE": "SUBSECRETARÍA TÉCNICA ADMINISTRATIVA Y LEGAL",
      "DIRECCIONES": {
        "OFICINAPRIVADA": {
          "NOMBRE": "OFICINA PRIVADA DE SUBSECRETARÍA TÉCNICA ADMINISTRATIVA Y LEGAL"
        },
        "DIRECCIONGENERALADMINISTRACION": {
          "NOMBRE": "DIRECCIÓN GENERAL DE ADMINISTRACIÓN",
          "DIRECCIONES": {
            "DIRECCIONGENERALADMINISTRACION": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONCONTABILIDAD": {
              "NOMBRE": "DIRECCIÓN DE CONTABILIDAD"
            },
            "DIRECCIONPRESUPUESTO": {
              "NOMBRE": "DIRECCIÓN DE PRESUPUESTO"
            },
            "DIRECCIONCOMPRASCONTRATACIONESSUMINISTROS": {
              "NOMBRE": "DIRECCIÓN DE COMPRAS, CONTRATACIONES Y SUMINISTROS"
            },
            "DIRECCIONTESORERIA": {
              "NOMBRE": "DIRECCIÓN DE TESORERÍA"
            },
            "DIRECCIONDELEGADAPERSONAL": {
              "NOMBRE": "DIRECCIÓN DELEGADA DE LA DIRECCIÓN PROVINCIAL DE PERSONAL"
            },
            "DIRECCIONTECNOLOGIAINFORMACION": {
              "NOMBRE": "DIRECCIÓN DE TECNOLOGÍA DE LA INFORMACIÓN",
            },
            "DIRECCIONSERVICIOSAUXILIARES": {
              "NOMBRE": "DIRECCIÓN DE SERVICIOS AUXILIARES"
            },
            "DIRECCIONSERVICIOSTECNICOS": {
              "NOMBRE": "DIRECCIÓN DE SERVICIOS TÉCNICOS"
            }
          }
        },
        "DIRECCIONGENERALTECNICALEGAL": {
          "NOMBRE": "DIRECCIÓN GENERAL TÉCNICA Y LEGAL",
          "DIRECCIONES": {
            "DIRECCIONGENERALTECNICALEGAL": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONTECNICOADMINISTRATIVA": {
              "NOMBRE": "DIRECCIÓN TÉCNICO ADMINISTRATIVA"
            },
            "DIRECCIONCOORDINACIONJURIDICA": {
              "NOMBRE": "DIRECCIÓN DE COORDINACIÓN JURÍDICA"
            },
            "DIRECCIONGESTIONMULTAS": {
              "NOMBRE": "DIRECCIÓN DE GESTIÓN DE MULTAS POR INFRACCIONES DE TRÁNSITO Y TRANSPORTE"
            }
          }
        }
      }
    },
    "SUBSECRETARIATRANSPORTEAEREOFLUVIAL": {
      "NOMBRE": "SUBSECRETARÍA DE TRANSPORTE AÉREO Y FLUVIAL",
      "DIRECCIONES": {
        "OFICINAPRIVADA": {
          "NOMBRE": "OFICINA PRIVADA DE SUBSECRETARÍA DE TRANSPORTE AÉREO Y FLUVIAL"
        },
        "DIRECCIONCONTRALORTRANSPORTEFLUVIAL": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE FLUVIAL DE PASAJEROS",
          "DIRECCIONES": {
            "DIRECCIONCONTRALORTRANSPORTEFLUVIAL": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONOPERACIONESTRANSPORTEFLUVIAL": {
              "NOMBRE": "DIRECCIÓN DE OPERACIONES DE TRANSPORTE FLUVIAL DE PASAJEROS"
            },
            "DIRECCIONFISCALIZACIONTRANSPORTEFLUVIAL": {
              "NOMBRE": "DIRECCIÓN DE FISCALIZACIÓN DEL TRANSPORTE FLUVIAL DE PASAJEROS"
            }
          }
        },
        "DIRECCIONCONTRALORTRANSPORTEAEREO": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE AÉREO",
          "DIRECCIONES": {
            "DIRECCIONCONTRALORTRANSPORTEAEREO": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONOPERACIONESTRANSPORTEAEREO": {
              "NOMBRE": "DIRECCIÓN DE OPERACIONES DEL TRANSPORTE AÉREO"
            },
            "DIRECCIONFISCALIZACIONAEROPORTUARIA": {
              "NOMBRE": "DIRECCIÓN DE FISCALIZACIÓN AEROPORTUARIA"
            }
          }
        },
        "DIRECCIONPROMOCIONCOORDINACIONTRANSPORTEAEREOFLUVIAL": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE PROMOCIÓN Y COORDINACIÓN DEL TRANSPORTE AÉREO Y FLUVIAL",
          "DIRECCIONES": {
            "DIRECCIONPROMOCIONCOORDINACIONTRANSPORTEAEREOFLUVIAL": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONESTRATEGIASPORTUARIASAEROPORTUARIAS": {
              "NOMBRE": "DIRECCIÓN DE ESTRATEGIAS PORTUARIAS Y AEROPORTUARIAS"
            },
            "DIRECCIONPROMOCIONDESARROLLOTRANSPORTEFLUVIAL": {
              "NOMBRE": "DIRECCIÓN DE PROMOCIÓN Y DESARROLLO DE TRANSPORTE FLUVIAL DE PASAJEROS"
            }
          }
        }
      }
    },
    "SUBSECRETARIAARTICULACIONINTERJURISDICCIONAL": {
      "NOMBRE": "SUBSECRETARÍA DE ARTICULACIÓN INTERJURISDICCIONAL DEL TRANSPORTE",
      "DIRECCIONES": {
        "OFICINAPRIVADA": {
          "NOMBRE": "OFICINA PRIVADA DE SUBSECRETARÍA DE ARTICULACIÓN INTERJURISDICCIONAL"
        },
        "DIRECCIONCOMPENSACIONESTRANSPORTE": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE COMPENSACIONES AL TRANSPORTE",
          "DIRECCIONES": {
            "DIRECCIONCOMPENSACIONESTRANSPORTE": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONLIQUIDACIONPAGO": {
              "NOMBRE": "DIRECCIÓN DE LIQUIDACIÓN Y PAGO"
            },
            "DIRECCIONCONTROLVERIFICACION": {
              "NOMBRE": "DIRECCIÓN DE CONTROL Y VERIFICACIÓN"
            }
          }
        },
        "DIRECCIONCOORDINACIONTRANSPORTE": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE COORDINACIÓN DEL TRANSPORTE",
          "DIRECCIONES": {
            "DIRECCIONCOORDINACIONTRANSPORTE": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONCOORDINACIONPUBLICO": {
              "NOMBRE": "DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PÚBLICO"
            },
            "DIRECCIONCOORDINACIONPRIVADO": {
              "NOMBRE": "DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PRIVADO"
            }
          }
        },
        "DIRECCIONPLANIFICACIONPOLITICAECONOMICA": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE PLANIFICACIÓN Y POLÍTICA ECONÓMICA DEL TRANSPORTE",
          "DIRECCIONES": {
            "DIRECCIONPLANIFICACIONPOLITICAECONOMICA": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONPLANIFICACIONTRANSPORTE": {
              "NOMBRE": "DIRECCIÓN DE PLANIFICACIÓN DEL TRANSPORTE"
            },
            "DIRECCIONANALISISTRANSPORTE": {
              "NOMBRE": "DIRECCIÓN DE ANÁLISIS EFICIENTE DEL TRANSPORTE"
            },
            "DIRECCIONGESTIONSUBSIDIOS": {
              "NOMBRE": "DIRECCIÓN DE GESTIÓN DE SUBSIDIOS AL TRANSPORTE"
            }
          }
        },
        "DIRECCIONPOLITICASGENEROINCLUSIVAS": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE POLÍTICAS DE GÉNERO Y ESTRATEGIAS INCLUSIVAS",
          "DIRECCIONES": {
            "DIRECCIONPOLITICASGENEROINCLUSIVAS": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONACCESIBILIDADTRANSPORTE": {
              "NOMBRE": "DIRECCIÓN DE ACCESIBILIDAD DEL TRANSPORTE"
            },
            "DIRECCIONINCLUSIONDIVERSIDAD": {
              "NOMBRE": "DIRECCIÓN DE INCLUSIÓN Y DIVERSIDAD"
            }
          }
        },
        "DIRECCIONPOLITICASEDUCATIVASPREVENCION": {
          "NOMBRE": "DIRECCIÓN PROVINCIAL DE POLÍTICAS EDUCATIVAS DE PREVENCIÓN",
          "DIRECCIONES": {
            "DIRECCIONPOLITICASEDUCATIVASPREVENCION": {
              "NOMBRE": "OFICINA PRIVADA DE LA MISMA DIRECCIÓN"
            },
            "DIRECCIONPROMOCIONNORMASCONVIVENCIA": {
              "NOMBRE": "DIRECCIÓN DE PROMOCIÓN DE NORMAS DE CONVIVENCIA CIUDADANA"
            },
            "DIRECCIONGESTIONINTERMINISTERIAL": {
              "NOMBRE": "DIRECCIÓN DE GESTIÓN INTERMINISTERIAL DE PREVENCIÓN Y CONCIENTIZACIÓN EN EL TRANSPORTE"
            }
          }
        }
      }
    }
  }
}