var data = {
  'SUBSECRETARIAS': {
    'UNIDADMONITOREO': {
      'NOMBRE': 'UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE',
      'DIRECTOR': 'RUBIO, LISANDRO',
      'OFICINAPRIVADA': {
        'NOMBRE': 'OFICINA PRIVADA DE UNIDAD DE MONITOREO Y REGISTRO GENERAL DE DATOS DEL TRANSPORTE'
      }
    },
    'DIRECCIONCOMUNICACION': {
      'NOMBRE': 'DIRECCIÓN DE COMUNICACIÓN Y RELACIÓN INSTITUCIONALES',
      'DIRECTOR': 'CAMETHO, MARÍA VIOLETA',
      'OFICINAPRIVADA': {
        'NOMBRE': 'OFICINA PRIVADA DE DIRECCIÓN DE COMUNICACIÓN Y RELACIÓN INSTITUCIONALES'
      }
    },
    'SUBSECRETARIATRANSPORTETERRESTRE': {
      'NOMBRE': 'SUBSECRETARÍA DE TRANSPORTE TERRESTRE',
      'DIRECTOR': 'PERDIGUERO, JULIO RAFAEL',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE LA SUBSECRETARÍA DE TRANSPORTE TERRESTRE'
        },
        'DIRECCIONFISCALIZACIONTRANSPORTE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE FISCALIZACIÓN DEL TRANSPORTE',
          'DIRECTOR': 'ANELLO, HORACIO OSCAR',
          'DIRECCIONES': {
            'DIRECCIONFISCALIZACIONTRANSPORTE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCION'
            },
            'DIRECCIÓNCONTROLTECNICO': {
              'NOMBRE': 'DIRECCIÓN DE CONTROL TÉCNICO',
              'DIRECTOR': 'ABELANDO, NÉSTOR ARIEL'
            },
            'DIRECCIÓNRECLAMOSSOLICITUDES': {
              'NOMBRE': 'DIRECCIÓN DE RECLAMOS Y SOLICITUDES',
              'DIRECTOR': 'VARVASINO, GUILLERMO DANIEL'
            }
          },

        },
        'DIRECCIONTRANSPORTEPASAJEROS': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE PASAJEROS',
          'DIRECTOR': 'MALDONADO, GONZALO EZEQUIEL',
          'DIRECCIONES': {
            'DIRECCIONTRANSPORTEPASAJEROS': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN'
            },
            'DIRECCIÓNTRANSPORTEAUTOMOTORPASAJEROS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE PASAJEROS',
              'DIRECTOR': ''
            },
            'DIRECCIONPERMISOSHABILITACIONESPASAJEROS': {
              'NOMBRE': 'DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE PASAJEROS',
              'DIRECTOR': 'RUIZ LAMÓN, GERMÁN'
            },
            'DIRECCIONTRANSPORTEFERROVIARIOPASAJEROS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE FERROVIARIO DE PASAJEROS',
              'DIRECTOR': 'HUERGO, GUILLERMO JORGE FEDERICO'
            }
          },

        },
        'DIRECCIONTRANSPORTECARGAS': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE TRANSPORTE DE CARGAS',
          'DIRECTOR': 'BETTILI, MIGUEL ÁNGEL',
          'DIRECCIONES': {
            'DIRECCIONTRANSPORTECARGAS': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN'
            },
            'DIRECCIONPERMISOSHABILITACIONESCARGAS': {
              'NOMBRE': 'DIRECCIÓN DE PERMISOS Y HABILITACIONES DE TRANSPORTE DE CARGAS',
              'DIRECTOR': 'ORTIZ, PABLO JORGE'
            },
            'DIRECCIONTRANSPORTEAUTOMOTORCARGAS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE AUTOMOTOR DE CARGAS',
              'DIRECTOR': 'ZARBO, JORGE ALBERTO'
            },
            'DIRECCIONTRANSPORTEFERROVIARIOCARGAS': {
              'NOMBRE': 'DIRECCIÓN DE TRANSPORTE FERROVIARIO DE CARGAS',
              'DIRECTOR': ''
            }
          },

        },
        'DIRECCIONAPTITUDCONDUCTORES': {
          'NOMBRE': 'DIRECCION PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO',
          'DIRECTOR': 'LABONIA, ROBERTO EDUARDO',
          'DIRECCIONES': {
            'DIRECCIONAPTITUDCONDUCTORES': {
              'NOMBRE': 'OFICINA PRIVADA DE DIRECCION PROVINCIAL DE APTITUD PSICOFISICA PARA CONDUCTORES DEL TRANSPORTE PUBLICO',
            },
            'DIRECCIONCOORDINACIONSERVICIOEVALUACIONPSICOFISICA': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN DEL SERVICIO DE EVALUACIÓN PSICOFÍSICA',
              'DIRECTOR': ''
            },
            'DIRECCIONCONTRALORMONITOREOEVALUACIONPSICOFISICA': {
              'NOMBRE': 'DIRECCIÓN DE CONTRALOR Y MONITOREO DE EVALUACIÓN PSICOFÍSICA',
              'DIRECTOR': 'LUFRANO, MARIANO NICOLÁS'
            },
          },

        },
        'DIRECCIONPOLITICASTRANSPORTESOSTENIBLE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE POLÍTICAS DE TRANSPORTE SOSTENIBLE',
          'DIRECTOR': 'CURE, MIRTHA GLORIA',
          'DIRECCIONES': {
            'DIRECCIONPOLITICASTRANSPORTESOSTENIBLE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN'
            },
            'DIRECCIONDESARROLLOSOSTENIBLETRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE DESARROLLO SOSTENIBLE DEL TRANSPORTE',
              'DIRECTOR': 'GARCIA, MARIO RAFAEL'
            },
            'DIRECCIONPROYECTOSESTRATEGICOS': {
              'NOMBRE': 'DIRECCIÓN DE PROYECTOS ESTRATÉGICOS',
              'DIRECTOR': 'CUPERTINO, VÍCTOR MANUEL'
            }
          },
          'DIRECTOR': ''
        },
        'DIRECCIONVERIFICACIONTECNICAVEHICULAR': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE VERIFICACIÓN TÉCNICA VEHICULAR',
          'DIRECTOR': 'LUFRANO TAMASI, HÉCTOR LUCIANO',
          'DIRECCIONES': {
            'DIRECCIONVERIFICACIONTECNICAVEHICULAR': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN'
            },
            'DIRECCIONAPOYOLEGALTECNICOADMIN': {
              'NOMBRE': 'DIRECCIÓN DE APOYO LEGAL Y TÉCNICO ADMINISTRATIVO',
              'DIRECTOR': 'CLUA, MARTÍN'
            },
            'DIRECCIONPLANIFICACIONCOORDSERVICIO': {
              'NOMBRE': 'DIRECCIÓN DE PLANIFICACIÓN Y COORDINACIÓN DEL SERVICIO',
              'DIRECTOR': 'ALBERTI, MARÍA ESTEFANÍA'
            },
            'DIRECCIONFISCALIZACIONCONTROL': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN Y CONTROL',
              'DIRECTOR': 'ASENSIO, FACUNDO'
            }
          }
        }
      },

    },
    'SUBSECRETARIAPOLITICASEGURIDADVIAL': {
      'NOMBRE': 'SUBSECRETARÍA DE POLÍTICA Y SEGURIDAD VIAL',
      'DIRECTOR': '',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA DE POLÍTICA Y SEGURIDAD VIAL'
        },
        'DIRECCIONLICENCIASCONDUCIRANTECEDENTESTRANSITO': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE LICENCIAS DE CONDUCIR Y ANTECEDENTES DE TRÁNSITO',
          'DIRECTOR': 'MIGLIAVACCA, LUCAS ROBERTO',
          'DIRECCIONES': {
            'DIRECCIONLICENCIASCONDUCIRANTECEDENTESTRANSITO': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN'
            },
            'DIRECCIONLICENCIASCONDUCIR': {
              'NOMBRE': 'DIRECCIÓN DE LICENCIAS DE CONDUCIR',
              'DIRECTOR': ''
            },
            'DIRECCIONANTECEDENTESINHABILITADOS': {
              'NOMBRE': 'DIRECCIÓN DE ANTECEDENTES E INHABILITADOS',
              'DIRECTOR': ''
            }
          },

        },
        'DIRECCIONOBSERVATORIOVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE OBSERVATORIO VIAL',
          'DIRECTOR': 'COUDANNES, CARLOS FACUNDO',
          'DIRECCIONES': {
            'DIRECCIONOBSERVATORIOVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN'
            },
            'DIRECCIONESTADISTICAVIAL': {
              'NOMBRE': 'DIRECCIÓN DE ESTADÍSTICA VIAL',
              'DIRECTOR': ''
            },
            'DIRECCIONCAPACITACIONENLACECOMUNITARIO': {
              'NOMBRE': 'DIRECCIÓN DE CAPACITACIÓN Y ENLACE COMUNITARIO',
              'DIRECTOR': 'DÍAZ, MARÍA GUILLERMINA'
            }
          },

        },
        'DIRECCIONFISCALIZACIONCONTROLTRANSITOSEGURIDADVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE FISCALIZACIÓN Y CONTROL DEL TRÁNSITO Y LA SEGURIDAD VIAL',
          'DIRECTOR': 'BLANCO, ALEJANDRO OSVALDO',
          'DIRECCIONES': {
            'DIRECCIONFISCALIZACIONCONTROLTRANSITOSEGURIDADVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONFISCALIZACIONCONTROLTRANSITOYSEGURIDADVIAL': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN Y CONTROL DEL TRÁNSITO  Y LA SEGURIDAD VIAL',
              'DIRECTOR': 'GOLDFAB, FEDERICO ARIEL'
            }
          },

        },
        'DIRECCIONAPOYOCOORDTECNICOADMINISTRATIVA': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE APOYO Y COORDINACIÓN TÉCNICO ADMINISTRATIVA',
          'DIRECTOR': 'MEIJIDE, MARCELA',
          'DIRECCIONES': {
            'JUZGADOSADMINISTRATIVOS': {
              'NOMBRE': 'JUZGADOS ADMINISTRATIVOS DE INFRACCIONES DE TRÁNSITO PROVINCIAL (I A XIII)',

            },
            'DIRECCIONAPOYOADMINISTRATIVO': {
              'NOMBRE': 'DIRECCIÓN DE APOYO ADMINISTRATIVO',
              'DIRECTOR': 'MURIAS, JORGELINA PAOLA'
            },
            'DIRECCIONCOORDINACIONJUSTICIAADMINISTRATIVA': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN Y ORGANIZACIÓN DE LA JUSTICIA ADMINISTRATIVA DE INFRACCIONES DE TRÁNSITO PROVINCIAL',
              'DIRECTOR': 'ANGELETTI ALVAREZ, MARÍA LAURA'
            },
            'DIRECCIONINFORMATICATECNOLOGIA': {
              'NOMBRE': 'DIRECCIÓN DE INFORMÁTICA Y TECNOLOGÍA',
              'DIRECTOR': 'FONTANARI, ANDREA LORENA'
            }
          }
        }
      },

    },
    'SUBSECRETARIATECNICAADMINISTRATIVALEGAL': {
      'NOMBRE': 'SUBSECRETARÍA TÉCNICA ADMINISTRATIVA Y LEGAL',
      'DIRECTOR': 'CINGOLANI, IGNACIO MARTÍN',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA TÉCNICA ADMINISTRATIVA Y LEGAL'
        },
        'DIRECCIONGENERALADMINISTRACION': {
          'NOMBRE': 'DIRECCIÓN GENERAL DE ADMINISTRACIÓN',
          'DIRECTOR': 'GIMÉNEZ, MARÍA DE LOURDES',
          'DIRECCIONES': {
            'DIRECCIONGENERALADMINISTRACION': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONCONTABILIDAD': {
              'NOMBRE': 'DIRECCIÓN DE CONTABILIDAD',
              'DIRECTOR': 'KLEICH, SOLANGE'
            },
            'DIRECCIONPRESUPUESTO': {
              'NOMBRE': 'DIRECCIÓN DE PRESUPUESTO',
              'DIRECTOR': 'ROMERO, AILÍN ISABEL'
            },
            'DIRECCIONCOMPRASCONTRATACIONESSUMINISTROS': {
              'NOMBRE': 'DIRECCIÓN DE COMPRAS, CONTRATACIONES Y SUMINISTROS',
              'DIRECTOR': 'PEDERNERA, GONZALO HERNÁN'
            },
            'DIRECCIONTESORERIA': {
              'NOMBRE': 'DIRECCIÓN DE TESORERÍA',
              'DIRECTOR': 'ARIBE PERUZZO, MARGARITA'
            },
            'DIRECCIONDELEGADAPERSONAL': {
              'NOMBRE': 'DIRECCIÓN DELEGADA DE LA DIRECCIÓN PROVINCIAL DE PERSONAL',
              'DIRECTOR': 'SCHMITZ, JULIETA LORELEY'
            },
            'DIRECCIONTECNOLOGIAINFORMACION': {
              'NOMBRE': 'DIRECCIÓN DE TECNOLOGÍA DE LA INFORMACIÓN',
              'DIRECTOR': 'PRETTI, GABRIEL ALEJANDRO'
            },
            'DIRECCIONSERVICIOSAUXILIARES': {
              'NOMBRE': 'DIRECCIÓN DE SERVICIOS AUXILIARES',
              'DIRECTOR': 'SABAT, SABRINA INÉS'
            },
            'DIRECCIONSERVICIOSTECNICOS': {
              'NOMBRE': 'DIRECCIÓN DE SERVICIOS TÉCNICOS',
              'DIRECTOR': 'SIMIONI, MARÍA VICTORIA'
            }
          },

        },
        'DIRECCIONGENERALTECNICALEGAL': {
          'NOMBRE': 'DIRECCIÓN GENERAL TÉCNICA Y LEGAL',
          'DIRECTOR': 'TABOLARO, CRISTINA ELSA',
          'DIRECCIONES': {
            'DIRECCIONGENERALTECNICALEGAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONTECNICOADMINISTRATIVA': {
              'NOMBRE': 'DIRECCIÓN TÉCNICO ADMINISTRATIVA',
              'DIRECTOR': 'CANAVESSI, EDUARDO FABIÁN'
            },
            'DIRECCIONCOORDINACIONJURIDICA': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN JURÍDICA',
              'DIRECTOR': 'ESTREBOU, MARÍA CECILIA'
            },
            'DIRECCIONGESTIONMULTAS': {
              'NOMBRE': 'DIRECCIÓN DE GESTIÓN DE MULTAS POR INFRACCIONES DE TRÁNSITO Y TRANSPORTE',
              'DIRECTOR': 'MAYOL, SONIA ANGÉLICA'
            }
          }
        }
      },

    },
    'SUBSECRETARIATRANSPORTEAEREOFLUVIAL': {
      'NOMBRE': 'SUBSECRETARÍA DE TRANSPORTE AÉREO Y FLUVIAL',
      'DIRECTOR': 'RICCIARDELLI, MAIRA ROCÍO',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA DE TRANSPORTE AÉREO Y FLUVIAL'
        },
        'DIRECCIONCONTRALORTRANSPORTEFLUVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE FLUVIAL DE PASAJEROS',
          'DIRECTOR': 'CAPRIOLI, SILVIO MAXIMILIANO',
          'DIRECCIONES': {
            'DIRECCIONCONTRALORTRANSPORTEFLUVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONOPERACIONESTRANSPORTEFLUVIAL': {
              'NOMBRE': 'DIRECCIÓN DE OPERACIONES DE TRANSPORTE FLUVIAL DE PASAJEROS',
              'DIRECTOR': 'MOULES, ANDRÉS GUILLERMO'
            },
            'DIRECCIONFISCALIZACIONTRANSPORTEFLUVIAL': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN DEL TRANSPORTE FLUVIAL DE PASAJEROS',
              'DIRECTOR': ''
            }
          },

        },
        'DIRECCIONCONTRALORTRANSPORTEAEREO': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE CONTRALOR DEL TRANSPORTE AÉREO',
          'DIRECTOR': 'CARBALLO, FABIÁN JULIÁN',
          'DIRECCIONES': {
            'DIRECCIONCONTRALORTRANSPORTEAEREO': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONOPERACIONESTRANSPORTEAEREO': {
              'NOMBRE': 'DIRECCIÓN DE OPERACIONES DEL TRANSPORTE AÉREO',
              'DIRECTOR': 'PARDI, NICOLÁS ALEJANDRO'
            },
            'DIRECCIONFISCALIZACIONAEROPORTUARIA': {
              'NOMBRE': 'DIRECCIÓN DE FISCALIZACIÓN AEROPORTUARIA',
              'DIRECTOR': 'ALTAMIRANO, KARINA ALEJANDRA'
            }
          },

        },
        'DIRECCIONPROMOCIONCOORDINACIONTRANSPORTEAEREOFLUVIAL': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE PROMOCIÓN Y COORDINACIÓN DEL TRANSPORTE AÉREO Y FLUVIAL',
          'DIRECTOR': 'LARROUDE, MARÍA DE LOS ÁNGELES',
          'DIRECCIONES': {
            'DIRECCIONPROMOCIONCOORDINACIONTRANSPORTEAEREOFLUVIAL': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONESTRATEGIASPORTUARIASAEROPORTUARIAS': {
              'NOMBRE': 'DIRECCIÓN DE ESTRATEGIAS PORTUARIAS Y AEROPORTUARIAS',
              'DIRECTOR': 'SUSINO, FABIÁN RODOLFO'
            },
            'DIRECCIONPROMOCIONDESARROLLOTRANSPORTEFLUVIAL': {
              'NOMBRE': 'DIRECCIÓN DE PROMOCIÓN Y DESARROLLO DE TRANSPORTE FLUVIAL DE PASAJEROS',
              'DIRECTOR': ''
            }
          }
        }
      },

    },
    'SUBSECRETARIAARTICULACIONINTERJURISDICCIONAL': {
      'NOMBRE': 'SUBSECRETARÍA DE ARTICULACIÓN INTERJURISDICCIONAL DEL TRANSPORTE',
      'DIRECTOR': '',
      'DIRECCIONES': {
        'OFICINAPRIVADA': {
          'NOMBRE': 'OFICINA PRIVADA DE SUBSECRETARÍA DE ARTICULACIÓN INTERJURISDICCIONAL',

        },
        'DIRECCIONCOMPENSACIONESTRANSPORTE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE COMPENSACIONES AL TRANSPORTE',
          'DIRECTOR': 'BRITOS, GASTÓN LEANDRO',
          'DIRECCIONES': {
            'DIRECCIONCOMPENSACIONESTRANSPORTE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONLIQUIDACIONPAGO': {
              'NOMBRE': 'DIRECCIÓN DE LIQUIDACIÓN Y PAGO',
              'DIRECTOR': 'VEIRAS, LAILA LUDMILA ELISA'
            },
            'DIRECCIONCONTROLVERIFICACION': {
              'NOMBRE': 'DIRECCIÓN DE CONTROL Y VERIFICACIÓN',
              'DIRECTOR': ''
            }
          },

        },
        'DIRECCIONCOORDINACIONTRANSPORTE': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE COORDINACIÓN DEL TRANSPORTE',
          'DIRECTOR': 'MARTINEZ NOVARA, MARÍA ERCILIA',
          'DIRECCIONES': {
            'DIRECCIONCOORDINACIONTRANSPORTE': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONCOORDINACIONPUBLICO': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PÚBLICO',
              'DIRECTOR': 'URRUTIA, MARÍA LUJÁN'
            },
            'DIRECCIONCOORDINACIONPRIVADO': {
              'NOMBRE': 'DIRECCIÓN DE COORDINACIÓN DEL TRANSPORTE CON EL SECTOR PRIVADO',
              'DIRECTOR': 'GOMEZ CORREA, MARÍA NOELIA'
            }
          },

        },
        'DIRECCIONPLANIFICACIONPOLITICAECONOMICA': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE PLANIFICACIÓN Y POLÍTICA ECONÓMICA DEL TRANSPORTE',
          'DIRECTOR': 'GALLARDO, JONATAN EZEQUIEL',
          'DIRECCIONES': {
            'DIRECCIONPLANIFICACIONPOLITICAECONOMICA': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONPLANIFICACIONTRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE PLANIFICACIÓN DEL TRANSPORTE',
              'DIRECTOR': 'MARTINI, MAYRA ELISABETH'
            },
            'DIRECCIONANALISISTRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE ANÁLISIS EFICIENTE DEL TRANSPORTE',
              'DIRECTOR': 'ECHAVE, FACUNDO JAVIER'
            },
            'DIRECCIONGESTIONSUBSIDIOS': {
              'NOMBRE': 'DIRECCIÓN DE GESTIÓN DE SUBSIDIOS AL TRANSPORTE',
              'DIRECTOR': 'ARROYO, FEDERICO GUSTAVO'
            }
          },

        },
        'DIRECCIONPOLITICASGENEROINCLUSIVAS': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE POLÍTICAS DE GÉNERO Y ESTRATEGIAS INCLUSIVAS',
          'DIRECTOR': 'BEDOURET, ANGELA',
          'DIRECCIONES': {
            'DIRECCIONPOLITICASGENEROINCLUSIVAS': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONACCESIBILIDADTRANSPORTE': {
              'NOMBRE': 'DIRECCIÓN DE ACCESIBILIDAD DEL TRANSPORTE',
              'DIRECTOR': 'DI YORIO, SILVINA CLAUDIA'
            },
            'DIRECCIONINCLUSIONDIVERSIDAD': {
              'NOMBRE': 'DIRECCIÓN DE INCLUSIÓN Y DIVERSIDAD',
              'DIRECTOR': 'BOCCALERI, MARÍA ROSA'
            }
          },

        },
        'DIRECCIONPOLITICASEDUCATIVASPREVENCION': {
          'NOMBRE': 'DIRECCIÓN PROVINCIAL DE POLÍTICAS EDUCATIVAS DE PREVENCIÓN',
          'DIRECTOR': 'SANTANDREA, DANIELA CECILIA',
          'DIRECCIONES': {
            'DIRECCIONPOLITICASEDUCATIVASPREVENCION': {
              'NOMBRE': 'OFICINA PRIVADA DE LA MISMA DIRECCIÓN',

            },
            'DIRECCIONPROMOCIONNORMASCONVIVENCIA': {
              'NOMBRE': 'DIRECCIÓN DE PROMOCIÓN DE NORMAS DE CONVIVENCIA CIUDADANA',
              'DIRECTOR': 'JAIME, MARÍA EUGENIA'
            },
            'DIRECCIONGESTIONINTERMINISTERIAL': {
              'NOMBRE': 'DIRECCIÓN DE GESTIÓN INTERMINISTERIAL DE PREVENCIÓN Y CONCIENTIZACIÓN EN EL TRANSPORTE',
              'DIRECTOR': 'TETTAMANTI, MILAGROS'
            }
          }
        }
      },

    }
  }
}